import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_items_report(output_path: str, items: list[dict], report_title: str = "Items Report"):
    """Generate a PDF report of all items. Returns the file path."""
    doc = SimpleDocTemplate(output_path, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=20, spaceAfter=20, textColor=HexColor("#1a1a2e"))
    elements.append(Paragraph(report_title, title_style))
    elements.append(Spacer(1, 12))

    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=10, textColor=HexColor("#666666"), spaceAfter=20)
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Total items: {len(items)}", subtitle_style))
    elements.append(Spacer(1, 20))

    if not items:
        empty_style = ParagraphStyle("Empty", parent=styles["Normal"], fontSize=12, textColor=HexColor("#999999"))
        elements.append(Paragraph("No items found.", empty_style))
    else:
        header = ["ID", "Name", "Description"]
        data = [header]
        for item in items:
            data.append([
                str(item.get("id", "")),
                item.get("name", ""),
                (item.get("description") or "")[:80],
            ])

        table = Table(data, colWidths=[0.6 * inch, 2 * inch, 4 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1a1a2e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#ffffff")),
            ("FONTSIZE", (0, 0), (-1, 0), 11),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 1), (-1, -1), 10),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#dddddd")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#f8f9fa"), HexColor("#ffffff")]),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(table)

    elements.append(Spacer(1, 30))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=HexColor("#aaaaaa"))
    elements.append(Paragraph("Generated by BE-04 Item Service", footer_style))

    doc.build(elements)
    return output_path
